- name: "Install system print client"
  ansible.builtin.include_tasks: print_client/main.yml

- name: "Install and configure Avahi"
  ansible.builtin.include_role:
    name: ans_role_config_avahi
  vars:
    enable_host_discovery_service: true

