- name: "Restart cupsd printer-server service"
  ansible.builtin.service:
    name: cupsd
    state: restarted
  become: true
  become_user: root
  listen: restart_cupsd_serice

- name: "Restart devfs service"
  ansible.builtin.service:
    name: devfs
    state: restarted
  become: true
  become_user: root
  listen: restart_devfs_serice

