- name: "Ensure 'cups' service is started, and enable it to start at boot"
  ansible.builtin.service:
    name: cups
    state: started
    enabled: yes
  become: true
  become_user: root
  notify:
    - restart_automatic_printing_services
    - "{{ notify_avahi_handler_on_auto_printing_change }}"

- name: "Configure '{{ linux_cups_settings_path }}' to abort jobs on printer error"
  ansible.builtin.lineinfile:
    path: "{{ linux_cups_settings_path }}"
    regexp: >-
      ^ErrorPolicy
    line: >-
      ErrorPolicy abort-job
    state: present
    create: no
  become: true
  become_user: root
  notify:
    - restart_automatic_printing_services
    - "{{ notify_avahi_handler_on_auto_printing_change }}"

