- name: "Disable systemd-resolved service, as it conflicts with avahi resolver"
  # see https://wiki.archlinux.org/title/Avahi#Installation
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: no
  become: true
  become_user: root

- name: "Install the 'avahi' service-discovery package"
  # see https://wiki.archlinux.org/title/CUPS#Network
  community.general.pacman:
    name: avahi
    state: present
  become: true
  become_user: root
  notify: restart_cups_print_client

- name: "Install the 'nss-mdns' hostname resolution package"
  # see https://wiki.archlinux.org/title/CUPS#Network
  community.general.pacman:
    name: nss-mdns
    state: present
    extra_args: "--asdeps"
  become: true
  become_user: root
  notify: restart_cups_print_client

- name: "Ensure 'avahi-daemon' service is started, and enable it to start at boot"
  # see https://wiki.archlinux.org/title/CUPS#Network
  ansible.builtin.service:
    name: avahi-daemon
    state: started
    enabled: yes
  become: true
  become_user: root
  notify: restart_cups_print_client

