# Follow all steps, for both print-server and print-client:
#  https://docs.freebsd.org/en/articles/cups/

- name: "Install CUPS and related packages"
  ansible.builtin.include_tasks: cups.yml

- name: "Configure devfs for CUPS support"
  ansible.builtin.include_tasks: devfs.yml

  - name: "Configure system-wide CUPS settings for all printers"
    ansible.builtin.include_tasks: settings.yml

