- name: "Configure '{{ freebsd_cups_settings_path }}' to abort jobs on printer error"
  ansible.builtin.lineinfile:
    path: "{{ freebsd_cups_settings_path }}"
    regexp: >-
      ^ErrorPolicy
    line: >-
      ErrorPolicy abort-job
    state: present
    create: no
  become: true
  become_user: root

