- name: "In '/etc/nsswitch.conf', make nss-mdns authoritative for avahi's .local domain"
  # see https://wiki.archlinux.org/title/Avahi#Hostname_resolution
  ansible.builtin.lineinfile:
    path: '/etc/nsswitch.conf'
    regexp: >-
      ^hosts: (.*myhostname) (resolve.*)$
    line: >-
      hosts: \1 mdns_minimal [NOTFOUND=return] \2
    state: present
    backrefs: yes
    backup: yes
  become: true
  become_user: root
  notify: restart_cups_print_client

